#----------------------------------------------------------------------
# This file was generated by C:\MITX\EPD\Scripts\img2py-script.py
#
from wx.lib.embeddedimage import PyEmbeddedImage

icon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABHNCSVQICAgIfAhkiAAAAl1J"
    "REFUWIXtlj1oFUEQx38z95QUfqQRLSxViIVYKIiFhR+VIBZqESSVINjYCYJ9IoJdsIkgFlaa"
    "xhAswisCgiAIifiBoGA0gRQhihrE5PZv8fbyLu/u8mJE07yBhd2Znd3fzuwOa+YJGym+obt3"
    "ADoAHYAOQAcAqOUHUyHVHPDEjOvmBrAQUr0GtgN7PTGAEFK9iD5bgAF37mGW188Cp+P86ZAq"
    "AT7n9joUbZgn9JnpJ2iPu8wTHoPME+6a6UPsC3Qu2hV1WVNuTqa7ZaZ6HM+ABs1W+GStBrAP"
    "CMB7zADORLpL5kaDkx/A3B+E9pq5BaXKxjslsrUqU1AlMyHVKXeeRUCAsdBYvBu46u2vUg04"
    "jgQwbsaSGjhtAb6HVGdbNgc4meVwjTJtRj1bQ029AwyZsRnojYTT8XRDCpoFxlo2X4u8DanO"
    "rzEyfMRskyeMhFS9oMvR8SWwCxiJQP3uPMVstGKx0dzcITMeRfA68KrCxzpfsjKlwqQU6ioa"
    "bqthm5TCfbX6uPW06JaU7+fHmZS+Avc7SEcwjkmML19A6SDmByou5H6gq9y0mrRWJvgi9+5C"
    "1YJ3ct9aWs0adgk+qajrV7Ovgn9JCgLiW+GU5j0WwkSb4+wu0e1Y1aMEYBtGXzH/gPthFBak"
    "MFWwm/W1gauQ8nBOVIbaPMHsisweyv1EIeTFFJS35TnlGwwK3sTczcv9YikQfP1rgOpCpJsx"
    "zPNgA9YcL4LdMACFBzLvbb6SsCSzYbALhTuUPUHz2grbuiqh0RVhfiFCDuC53I8iFv8twHqk"
    "CuA/lmKj7EfyGx6OI2XEJyhqAAAAAElFTkSuQmCC")
geticonData = icon.GetData
geticonImage = icon.GetImage
geticonBitmap = icon.GetBitmap

